TEMPLATE = app
CONFIG += console
CONFIG -= qt

SOURCES += \
    ../../../Common/include/vector_structure.inl \
    ../../../Common/include/primal_grid_structure.inl \
    ../../../Common/include/matrix_structure.inl \
    ../../../Common/include/linear_solvers_structure.inl \
    ../../../Common/include/grid_movement_structure.inl \
    ../../../Common/include/grid_adaptation_structure.inl \
    ../../../Common/include/geometry_structure.inl \
    ../../../Common/include/dual_grid_structure.inl \
    ../../../Common/include/config_structure.inl \
    ../../../Common/src/vector_structure.cpp \
    ../../../Common/src/primal_grid_structure.cpp \
    ../../../Common/src/matrix_structure.cpp \
    ../../../Common/src/linear_solvers_structure.cpp \
    ../../../Common/src/grid_movement_structure.cpp \
    ../../../Common/src/grid_adaptation_structure.cpp \
    ../../../Common/src/geometry_structure.cpp \
    ../../../Common/src/dual_grid_structure.cpp \
    ../../../Common/src/config_structure.cpp \
    ../../../SU2_CFD/include/variable_structure.inl \
    ../../../SU2_CFD/include/solver_structure.inl \
    ../../../SU2_CFD/include/numerics_structure.inl \
    ../../../SU2_CFD/include/numerics_machine_learning.inl \
    ../../../SU2_CFD/include/integration_structure.inl \
    ../../../SU2_CFD/src/variable_template.cpp \
    ../../../SU2_CFD/src/variable_structure.cpp \
    ../../../SU2_CFD/src/variable_linearized_turbulent.cpp \
    ../../../SU2_CFD/src/variable_linearized_mean.cpp \
    ../../../SU2_CFD/src/variable_direct_wave.cpp \
    ../../../SU2_CFD/src/variable_direct_turbulent.cpp \
    ../../../SU2_CFD/src/variable_direct_transition.cpp \
    ../../../SU2_CFD/src/variable_direct_tne2.cpp \
    ../../../SU2_CFD/src/variable_direct_poisson.cpp \
    ../../../SU2_CFD/src/variable_direct_mean.cpp \
    ../../../SU2_CFD/src/variable_direct_heat.cpp \
    ../../../SU2_CFD/src/variable_direct_elasticity.cpp \
    ../../../SU2_CFD/src/variable_adjoint_turbulent.cpp \
    ../../../SU2_CFD/src/variable_adjoint_tne2.cpp \
    ../../../SU2_CFD/src/variable_adjoint_mean.cpp \
    ../../../SU2_CFD/src/variable_adjoint_levelset.cpp \
    ../../../SU2_CFD/src/SU2_CFD.cpp \
    ../../../SU2_CFD/src/solver_template.cpp \
    ../../../SU2_CFD/src/solver_structure.cpp \
    ../../../SU2_CFD/src/solver_linearized_turbulent.cpp \
    ../../../SU2_CFD/src/solver_linearized_mean.cpp \
    ../../../SU2_CFD/src/solver_direct_wave.cpp \
    ../../../SU2_CFD/src/solver_direct_turbulent.cpp \
    ../../../SU2_CFD/src/solver_direct_transition.cpp \
    ../../../SU2_CFD/src/solver_direct_tne2.cpp \
    ../../../SU2_CFD/src/solver_direct_poisson.cpp \
    ../../../SU2_CFD/src/solver_direct_mean.cpp \
    ../../../SU2_CFD/src/solver_direct_heat.cpp \
    ../../../SU2_CFD/src/solver_direct_elasticity.cpp \
    ../../../SU2_CFD/src/solver_adjoint_turbulent.cpp \
    ../../../SU2_CFD/src/solver_adjoint_tne2.cpp \
    ../../../SU2_CFD/src/solver_adjoint_mean.cpp \
    ../../../SU2_CFD/src/solver_adjoint_levelset.cpp \
    ../../../SU2_CFD/src/output_tecplot.cpp \
    ../../../SU2_CFD/src/output_structure.cpp \
    ../../../SU2_CFD/src/output_paraview.cpp \
    ../../../SU2_CFD/src/output_cgns.cpp \
    ../../../SU2_CFD/src/numerics_template.cpp \
    ../../../SU2_CFD/src/numerics_structure.cpp \
    ../../../SU2_CFD/src/numerics_machine_learning_turbulent.cpp \
    ../../../SU2_CFD/src/numerics_machine_learning.cpp \
    ../../../SU2_CFD/src/numerics_linearized_turbulent.cpp \
    ../../../SU2_CFD/src/numerics_linearized_mean.cpp \
    ../../../SU2_CFD/src/numerics_direct_wave.cpp \
    ../../../SU2_CFD/src/numerics_direct_turbulent.cpp \
    ../../../SU2_CFD/src/numerics_direct_transition.cpp \
    ../../../SU2_CFD/src/numerics_direct_tne2.cpp \
    ../../../SU2_CFD/src/numerics_direct_poisson.cpp \
    ../../../SU2_CFD/src/numerics_direct_mean.cpp \
    ../../../SU2_CFD/src/numerics_direct_heat.cpp \
    ../../../SU2_CFD/src/numerics_direct_elasticity.cpp \
    ../../../SU2_CFD/src/numerics_adjoint_turbulent.cpp \
    ../../../SU2_CFD/src/numerics_adjoint_tne2.cpp \
    ../../../SU2_CFD/src/numerics_adjoint_mean.cpp \
    ../../../SU2_CFD/src/numerics_adjoint_levelset.cpp \
    ../../../SU2_CFD/src/iteration_structure.cpp \
    ../../../SU2_CFD/src/integration_time.cpp \
    ../../../SU2_CFD/src/integration_structure.cpp \
    ../../../SU2_CFD/src/definition_structure.cpp \
    ../../../SU2_DDC/src/SU2_DDC.cpp \
    ../../../SU2_GDC/src/SU2_GDC.cpp \
    ../../../SU2_GPC/src/SU2_GPC.cpp \
    ../../../SU2_MAC/src/SU2_MAC.cpp \
    ../../../SU2_MDC/src/SU2_MDC.cpp \
    ../../../SU2_PBC/src/SU2_PBC.cpp \
    ../../../SU2_SOL/src/SU2_SOL.cpp \
    ../../../SU2_UMC/src/SU2_UMC.cpp

HEADERS += \
    ../../../Common/include/vector_structure.hpp \
    ../../../Common/include/primal_grid_structure.hpp \
    ../../../Common/include/option_structure.hpp \
    ../../../Common/include/matrix_structure.hpp \
    ../../../Common/include/linear_solvers_structure.hpp \
    ../../../Common/include/grid_movement_structure.hpp \
    ../../../Common/include/grid_adaptation_structure.hpp \
    ../../../Common/include/geometry_structure.hpp \
    ../../../Common/include/dual_grid_structure.hpp \
    ../../../Common/include/config_structure.hpp \
    ../../../SU2_CFD/include/variable_structure.hpp \
    ../../../SU2_CFD/include/SU2_CFD.hpp \
    ../../../SU2_CFD/include/solver_structure.hpp \
    ../../../SU2_CFD/include/output_structure.hpp \
    ../../../SU2_CFD/include/numerics_structure.hpp \
    ../../../SU2_CFD/include/numerics_machine_learning_turbulent.hpp \
    ../../../SU2_CFD/include/numerics_machine_learning.hpp \
    ../../../SU2_CFD/include/iteration_structure.hpp \
    ../../../SU2_CFD/include/integration_structure.hpp \
    ../../../SU2_CFD/include/definition_structure.hpp \
    ../../../SU2_DDC/include/SU2_DDC.hpp \
    ../../../SU2_GDC/include/SU2_GDC.hpp \
    ../../../SU2_GPC/include/SU2_GPC.hpp \
    ../../../SU2_MAC/include/SU2_MAC.hpp \
    ../../../SU2_MDC/include/SU2_MDC.hpp \
    ../../../SU2_PBC/include/SU2_PBC.hpp \
    ../../../SU2_SOL/include/SU2_SOL.hpp \
    ../../../SU2_UMC/include/SU2_UMC.hpp

OTHER_FILES += \
    ../../../Common/src/libSU2_a-vector_structure.o \
    ../../../Common/src/libSU2_a-primal_grid_structure.o \
    ../../../Common/src/libSU2_a-matrix_structure.o \
    ../../../Common/src/libSU2_a-linear_solvers_structure.o \
    ../../../Common/src/libSU2_a-grid_movement_structure.o \
    ../../../Common/src/libSU2_a-grid_adaptation_structure.o \
    ../../../Common/src/libSU2_a-geometry_structure.o \
    ../../../Common/src/libSU2_a-dual_grid_structure.o \
    ../../../Common/src/libSU2_a-config_structure.o \
    ../../../SU2_CFD/src/___bin_SU2_SOL-variable_structure.o \
    ../../../SU2_CFD/src/___bin_SU2_SOL-solver_structure.o \
    ../../../SU2_CFD/src/___bin_SU2_SOL-output_tecplot.o \
    ../../../SU2_CFD/src/___bin_SU2_SOL-output_structure.o \
    ../../../SU2_CFD/src/___bin_SU2_SOL-output_paraview.o \
    ../../../SU2_CFD/src/___bin_SU2_SOL-output_cgns.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_template.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_structure.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_linearized_turbulent.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_linearized_mean.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_direct_wave.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_direct_turbulent.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_direct_transition.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_direct_tne2.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_direct_poisson.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_direct_mean.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_direct_heat.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_direct_elasticity.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_adjoint_turbulent.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_adjoint_tne2.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_adjoint_mean.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-variable_adjoint_levelset.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-SU2_CFD.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_template.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_structure.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_linearized_turbulent.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_linearized_mean.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_direct_wave.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_direct_turbulent.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_direct_transition.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_direct_tne2.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_direct_poisson.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_direct_mean.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_direct_heat.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_direct_elasticity.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_adjoint_turbulent.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_adjoint_tne2.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_adjoint_mean.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-solver_adjoint_levelset.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-output_tecplot.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-output_structure.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-output_paraview.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-output_cgns.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_template.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_structure.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_machine_learning_turbulent.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_machine_learning.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_linearized_turbulent.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_linearized_mean.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_direct_wave.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_direct_turbulent.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_direct_transition.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_direct_tne2.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_direct_poisson.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_direct_mean.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_direct_heat.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_direct_elasticity.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_adjoint_turbulent.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_adjoint_tne2.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_adjoint_mean.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-numerics_adjoint_levelset.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-iteration_structure.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-integration_time.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-integration_structure.o \
    ../../../SU2_CFD/src/___bin_SU2_CFD-definition_structure.o \
    ../../../SU2_DDC/src/___bin_SU2_DDC-SU2_DDC.o \
    ../../../SU2_GDC/src/___bin_SU2_GDC-SU2_GDC.o \
    ../../../SU2_GPC/src/___bin_SU2_GPC-SU2_GPC.o \
    ../../../SU2_MAC/src/___bin_SU2_MAC-SU2_MAC.o \
    ../../../SU2_MDC/src/___bin_SU2_MDC-SU2_MDC.o \
    ../../../SU2_PBC/src/___bin_SU2_PBC-SU2_PBC.o \
    ../../../SU2_SOL/src/___bin_SU2_SOL-SU2_SOL.o \
    ../../../SU2_UMC/src/___bin_SU2_UMC-SU2_UMC.o

